/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package local.test.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Test extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7858989520125963955L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Test\",\"namespace\":\"local.test.avro\",\"fields\":[{\"name\":\"include\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"exclude\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Test> ENCODER =
      new BinaryMessageEncoder<Test>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Test> DECODER =
      new BinaryMessageDecoder<Test>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Test> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Test> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Test> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Test>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Test to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Test from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Test instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Test fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.Integer include;
  private java.lang.CharSequence exclude;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Test() {}

  /**
   * All-args constructor.
   * @param include The new value for include
   * @param exclude The new value for exclude
   */
  public Test(java.lang.Integer include, java.lang.CharSequence exclude) {
    this.include = include;
    this.exclude = exclude;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return include;
    case 1: return exclude;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: include = (java.lang.Integer)value$; break;
    case 1: exclude = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'include' field.
   * @return The value of the 'include' field.
   */
  public java.lang.Integer getInclude() {
    return include;
  }


  /**
   * Sets the value of the 'include' field.
   * @param value the value to set.
   */
  public void setInclude(java.lang.Integer value) {
    this.include = value;
  }

  /**
   * Gets the value of the 'exclude' field.
   * @return The value of the 'exclude' field.
   */
  public java.lang.CharSequence getExclude() {
    return exclude;
  }


  /**
   * Sets the value of the 'exclude' field.
   * @param value the value to set.
   */
  public void setExclude(java.lang.CharSequence value) {
    this.exclude = value;
  }

  /**
   * Creates a new Test RecordBuilder.
   * @return A new Test RecordBuilder
   */
  public static local.test.avro.Test.Builder newBuilder() {
    return new local.test.avro.Test.Builder();
  }

  /**
   * Creates a new Test RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Test RecordBuilder
   */
  public static local.test.avro.Test.Builder newBuilder(local.test.avro.Test.Builder other) {
    if (other == null) {
      return new local.test.avro.Test.Builder();
    } else {
      return new local.test.avro.Test.Builder(other);
    }
  }

  /**
   * Creates a new Test RecordBuilder by copying an existing Test instance.
   * @param other The existing instance to copy.
   * @return A new Test RecordBuilder
   */
  public static local.test.avro.Test.Builder newBuilder(local.test.avro.Test other) {
    if (other == null) {
      return new local.test.avro.Test.Builder();
    } else {
      return new local.test.avro.Test.Builder(other);
    }
  }

  /**
   * RecordBuilder for Test instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Test>
    implements org.apache.avro.data.RecordBuilder<Test> {

    private java.lang.Integer include;
    private java.lang.CharSequence exclude;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(local.test.avro.Test.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.include)) {
        this.include = data().deepCopy(fields()[0].schema(), other.include);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.exclude)) {
        this.exclude = data().deepCopy(fields()[1].schema(), other.exclude);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing Test instance
     * @param other The existing instance to copy.
     */
    private Builder(local.test.avro.Test other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.include)) {
        this.include = data().deepCopy(fields()[0].schema(), other.include);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.exclude)) {
        this.exclude = data().deepCopy(fields()[1].schema(), other.exclude);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'include' field.
      * @return The value.
      */
    public java.lang.Integer getInclude() {
      return include;
    }


    /**
      * Sets the value of the 'include' field.
      * @param value The value of 'include'.
      * @return This builder.
      */
    public local.test.avro.Test.Builder setInclude(java.lang.Integer value) {
      validate(fields()[0], value);
      this.include = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'include' field has been set.
      * @return True if the 'include' field has been set, false otherwise.
      */
    public boolean hasInclude() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'include' field.
      * @return This builder.
      */
    public local.test.avro.Test.Builder clearInclude() {
      include = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'exclude' field.
      * @return The value.
      */
    public java.lang.CharSequence getExclude() {
      return exclude;
    }


    /**
      * Sets the value of the 'exclude' field.
      * @param value The value of 'exclude'.
      * @return This builder.
      */
    public local.test.avro.Test.Builder setExclude(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.exclude = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'exclude' field has been set.
      * @return True if the 'exclude' field has been set, false otherwise.
      */
    public boolean hasExclude() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'exclude' field.
      * @return This builder.
      */
    public local.test.avro.Test.Builder clearExclude() {
      exclude = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Test build() {
      try {
        Test record = new Test();
        record.include = fieldSetFlags()[0] ? this.include : (java.lang.Integer) defaultValue(fields()[0]);
        record.exclude = fieldSetFlags()[1] ? this.exclude : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Test>
    WRITER$ = (org.apache.avro.io.DatumWriter<Test>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Test>
    READER$ = (org.apache.avro.io.DatumReader<Test>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.include == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.include);
    }

    if (this.exclude == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.exclude);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.include = null;
      } else {
        this.include = in.readInt();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.exclude = null;
      } else {
        this.exclude = in.readString(this.exclude instanceof Utf8 ? (Utf8)this.exclude : null);
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.include = null;
          } else {
            this.include = in.readInt();
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.exclude = null;
          } else {
            this.exclude = in.readString(this.exclude instanceof Utf8 ? (Utf8)this.exclude : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










